### ISSUE TITLE
Create ERD Diagram 

### ISSUE THREAD

**Issue by thechandanbhagat** [chandan-g-bhagat/broadway-430-proj#7]
All should create the ERD Diagram for the School Management System

**Comment by guddi-hp** [comment]
![Screenshot (93)](https://user-images.githubusercontent.com/78401336/118923429-407c9100-b95b-11eb-802d-7c008bc78473.png)
School management System er diagram.

**Comment by KshittizChaudhary950** [comment]
![IMG_20210520_115437](https://user-images.githubusercontent.com/80756978/118928120-7d985180-b962-11eb-931d-23aae1f70036.jpg)

**Comment by zeus-amit** [comment]
![er-sms-broadway](https://user-images.githubusercontent.com/80759901/118950705-2900d080-b97a-11eb-842d-7100eb807a35.jpg)

**Comment by anchallama** [comment]
![ER digram](https://user-images.githubusercontent.com/78376419/118965320-4b014f80-b988-11eb-9e74-34e88d3470f8.jpg)

**Comment by Saroj404** [comment]
![SarojShERD](https://user-images.githubusercontent.com/30053153/118965349-55234e00-b988-11eb-8515-bb4357c83582.png)

**Comment by Himanshuk-55** [comment]
![Untitled](https://user-images.githubusercontent.com/67067810/118969167-c3412400-b93a-11eb-930a-22f2338197c0.png)

**Comment by thechandanbhagat** [comment]
![SchoolManagementSystemERD](https://user-images.githubusercontent.com/6848264/118976021-45aa0200-b994-11eb-9d5a-18dc539f1f2b.png)

**Comment by zeus-amit** [comment]
Issue Closed
